spring:
  application:
    name: comment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ciyfminicabg.ap-northeast-2.rds.amazonaws.com:3306/comment_service
    username: admin
    password: djmw3113
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger.html
server:
  port: 8080
