spring:
  application:
    name: user-service
  profiles:
    include=oauth:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hs-spring-db.cjhazvr1oeo5.ap-northeast-2.rds.amazonaws.com:3306/weatherfit
    username: wlfkrdl2
    password: gmltjd36!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 453423602833-7db2b1dbicre47rkcrpfgn20nd16l9rs.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
  mail:
    host: smtp.gmail.com
    port: 587
    username: wlfkrdl2@gmail.com
    password: hnqp swqi hxeh xjee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분
logging:
  level:
    org.springframework.security.web: trace
    com.weather.user: debug

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
server:
  port: 8080

