server:
  port: 8080

spring:
  application:
    name: api_gateway_service
  cloud:
    gateway:
      routes:
        - id : user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: lb://board-service
          predicates:
            - Path=/board-service/**
          filters:
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
        - id: nodejs-service
          uri: lb://nodejs-service
          predicates:
            - Path=/nodejs-service/**
          filters:
            - RewritePath=/nodejs-service/(?<segment>.*), /$\{segment}
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**
          filters:
            - RewritePath=/test-service/(?<segment>.*), /$\{segment}
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comment/**
          filters:
            - RewritePath=/comment/(?<segment>.*), /$\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka