name: Java CI with Gradle

on:
  push:
    paths:
      - 'test_service/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'test_service/**'
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name : permission for gradlew
        run : chmod +x gradlew

      - name: Build with Gradle
          # uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
          # with:
        # arguments: build
        run : ./gradlew clean build --exclude-task test

      - name : 도커 이미지 빌드
        run : docker build -t jerneithe/node_service .

      - name : 도커 허브 로그인
        uses : docker/login-action@v2
        with :
          username : ${{ secrets.TEST_SERVICE_DOCKERHUB_USERNAME }}
          password : ${{ secrets.TEST_SERVICE_DOCKERHUB_TOKEN }}

      - name : 도커 퍼블리싱
        run : docker push jerneithe/node_service

      - name : ec2 접속 및 애플리케이션 실행
        uses : appleboy/ssh-action@v0.1.6
        with :
          host : ${{ secrets.EC2_HOST }}
          username : ubuntu
          key : ${{ secrets.EC2_PEMKEY }}
          port : 22
          script : |
            sudo docker stop $(sudo docker ps -a -q)
            sudo docker rm $(sudo docker ps -a pq)
            sudo docker pull jerneithe/node_service
            sudo docker run -d -p 8004:8004 jerneithe/node_service
